---
- name: Install Jupyter through pip
  become: true
  shell: |
     sudo pip install jupyter notebook
  args:
      executable: /bin/bash
  register: jupyter

- name: Install Jupyter and Generate jupyter config file
  become: false
  shell: |
     jupyter notebook --generate-config
     python -m pip install --upgrade pip

  args:
    executable: /bin/bash
  when: jupyter.changed
  register: config

- name: changing Jupyter config file
  lineinfile:
     path: /home/ubuntu/.jupyter/jupyter_notebook_config.py
     line: |
         c.NotebookApp.ip = '*'
         c.NotebookApp.port = 9999
  when: config.changed