- hosts: webserver
  become_user: root
  become: true
  become_method: sudo


    

  vars:
    - path: /root/ansible_scripts/files/index.html

      ubuntu_php_pkgs:
         - php5-fpm
         - php5-cgi
         - php5-cli
         - php5-curl
         - php5-json
         - php5-odbc
         - php5-tidy
         - php5-common
         - php5-xmlrpc
         - php5-gd
         - php-pear
         - php5-dev
         - php5-imap
         - php5-mcrypt
         - php5-mysql
         - libapache2-mod-php5


  roles:
    - WebApplication