- hosts: dbserver
  become_user: root
  become: true
  become_method: sudo

  vars:
    - path: /root/ansible_scripts/files/abc.sql
      mysql_port: 3306 #Default is 3306, please change it if you are using non-standard
      mysql_bind_address: "0.0.0.0" #Change it to 0.0.0.0,if you want to listen everywhere
      mysql_user: root
      mysql_root_pass: admin #MySQL Root Password


      ubuntu_mysql_pkgs:
         - mysql-server
         - mysql-client
         - python-mysqldb
         - libmysqlclient-dev


  roles:
    - DBApplication