---
# Handler for the webtier: handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: start apache2
  service: name=apache2 state=started

- name: restart apache2
  service: name=apache2 state=restarted
