---
- name: Install NodeJS Packages
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
      "{{ ubuntu_nodejs_pkgs }}"

- name: Delete directory
  file: path=/home/ubuntu/src/webApp state=absent

- name: Create directory
  file: path=/home/ubuntu/src/webApp state=directory mode=0777
  register: create

- name: Git Clone Repo
  git:
    repo: "{{ path }}"
    dest: /home/ubuntu/src/webApp
  register: git_finished
  when: create.changed

- name: Update npm
  npm: name=npm global=yes production=yes
  register: npm_finished
  when: git_finished.changed

- name: Install npm packages
  become_user: root
  become: true
  become_method: sudo
  shell: chdir=/home/ubuntu/src/webApp npm install
  register: npmPkg
  when: npm_finished.changed

- name: Install pm2
  npm: name=pm2 global=yes production=yes
  register: pm2_finished
  when: npmPkg.changed

- name: Install shelljs
  become_user: root
  become: true
  become_method: sudo
  shell: chdir=/home/ubuntu/src/webApp npm install shelljs
  register: shelljs_finished
  when: npmPkg.changed

- name: Stop APP
  become_user: root
  command: pm2 stop index chdir=/home/ubuntu/src/webApp
  ignore_errors: yes

- name: Start APP
  become_user: root
  command: pm2 start index.js chdir=/home/ubuntu/src/webApp
  ignore_errors: yes
  when:
     - pm2_finished.changed
     - shelljs_finished.changed